server {
    listen 80;
    listen [::]:80;
    server_name pentaworks.net;

    return 302 https://app.pentaworks.net$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name pentaworks.net;

    ssl_certificate /etc/letsencrypt/live/pentaworks.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pentaworks.net/privkey.pem;

    return 302 https://app.pentaworks.net$request_uri;
}
