-- Keep raw readings; exclude negative and 0.1 readings consistently from display, averages and alerts.
ALTER TABLE mrtb
    MODIFY COLUMN recosi_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN recosi_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`recosi`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN coldtp_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN coldtp_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`coldtp`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN recoru_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN recoru_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`recoru`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN hepres_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN hepres_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`hepres`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN heleve_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN heleve_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`heleve`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN actemp_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN actemp_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`actemp`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN achumi_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN achumi_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`achumi`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN gctemp_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN gctemp_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`gctemp`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN gcflow_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN gcflow_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`gcflow`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN cctemp_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN cctemp_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`cctemp`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT,
    MODIFY COLUMN ccflow_value DOUBLE AS (CASE WHEN REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') AS DOUBLE) NOT IN (0, 0.001, 0.01, 0.1) AND CAST(REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') AS DOUBLE) > 0 THEN CAST(REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') AS DOUBLE) ELSE NULL END) PERSISTENT,
    MODIFY COLUMN ccflow_unmeasured TINYINT(1) AS (CASE WHEN REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') AS DOUBLE) <= 0 THEN 1 WHEN REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') REGEXP '^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$' AND CAST(REGEXP_REPLACE(TRIM(`ccflow`), '[^0-9.+-]', '') AS DOUBLE) IN (0.001, 0.01, 0.1) THEN 1 ELSE 0 END) PERSISTENT;

-- Retain historical events, but stop outstanding notifications for invalid measurements.
UPDATE alert_event e JOIN alert_rule r ON r.id=e.rule_id
SET e.recovered_at=CURRENT_TIMESTAMP(6),
    e.delivery_status=CASE WHEN e.delivery_status IN ('PENDING','FAILED','PARTIAL') THEN 'SKIPPED' ELSE e.delivery_status END
WHERE r.rule_type='RANGE' AND e.event_type IN ('LOW','HIGH')
  AND e.recovered_at IS NULL
  AND (e.measured_value<=0 OR e.measured_value IN (0.001,0.01,0.1));
